services:
  - type: web
    name: heavencraft
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "HandmadeMart.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SESSION_SECRET
        generateValue: true
      - key: FLASK_APP
        value: "HandmadeMart.app"
      - key: FLASK_ENV
        value: production