services:
  - type: web
    name: havencraft-website
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn "wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_APP
        value: "HandmadeMart.app"
      - key: FLASK_ENV
        value: "production"
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: havencraft-db
          property: connectionString

  - type: postgres
    name: havencraft-db
    plan: free
    databaseName: havencraft
    user: havencraft_user